package hired

//Auto generated code for hiring workers.
//DO NOT EDIT THIS FILE.
import worker "github.com/herb-go/worker"

func init() {
	//Worker "hired.LocalPersist"
	worker.Hire("hired.LocalPersist", &LocalPersist).
		WithIntroduction("local persist factory")

}