#time.toml is app time display format config file.
#Formats are in golang time format like 2006-01-02 15:04:05.
#See also https://golang.org/pkg/time/

#Timezone string value of app timezone.
#Default value is server local time zone.
	Timezone       = "Asia/Shanghai"

#TimeFormat default time format used in app.
#Default value is 15:04:05
#	TimeFormat     = ""

#DateFormat Default date format used in app.
#Default value is "2006-01-02"
#	DateFormat     =""

#DatetimeFormat Default date time fromat used in app.
#Default value is "2006-01-02 15:04:05"
#	DatetimeFormat =""
