Type="lua"
Intro=""
Desc=""
OnOpen="onOpen"
OnClose="onClose"
OnConnect="onConnected"
OnDisconnect="onDisconnected"
OnBroadcast="onBroadcast"
OnResponse="onResponse"
OnAssist = "onAssist"
OnKeyUp = "onKeyup"
Channel=""