[Config]
#Network network which server should listen.
#For http server,Net value should always be "tcp"
Net="tcp"
#Ip address and port which  server should listen.
#For example:
#   Addr= ":8000" listent to port 8000 on all address
#   Addr= "127.0.0.1:8000" listent to port 8000 on localhost
#   Addr= "8.8.8.8:8000" listent to port 8000 on ip 8.8.8.8
#See also https://golang.org/pkg/net/#Dial
Addr= ":8000"
BaseURL= "http://localhost:8000"
#ReadTimeoutInSecond is the maximum duration for reading the entire
#request, including the body.
#   ReadTimeoutInSecond= 30
#ReadHeaderTimeoutInSecond is the amount of time allowed to read
#request headers. 
#   ReadHeaderTimeoutInSecond=20
#WriteTimeoutInSecond is the maximum duration before timing out
#writes of the response.
#   WriteTimeoutInSecond=30
#IdleTimeoutInSecond is the maximum amount of time to wait for the
#next request when keep-alives are enabled.
#   IdleTimeoutInSecond=30
#MaxHeaderBytes controls the maximum number of bytes the
#server will read parsing the request header's keys and
#values, including the request line. It does not limit the
#size of the request body.
#   MaxHeaderBytes=100000
[Forwarded]
#Config for Forwarded middleware which decide how to trust proxy info in http header.
#Enabled if Forwarded middleware is enabled.
Enabled=false
#ForwardedForHeader request header name which stores real ip.
#If set to empty string,this feature will be disabeld.
ForwardedForHeader="X-Forwarded-For"
#ForwardedHostHeader request header name which stores real host.
#If set to empty string,this feature will be disabeld.
ForwardedHostHeader="X-Forwarded-Host"
#ForwardedProtoHeader request header name which stores real proto.
#If set to empty string,this feature will be disabeld.
ForwardedProtoHeader="X-Forwarded-Proto"
#ForwardedTokenHeader request header name which stores token.
#If set to empty string,this feature will be disabeld.
ForwardedTokenHeader=""
#ForwardedTokenValue value which request header must equal.
ForwardedTokenValue="token"
#Headers headers which will be added to every http response.
[Headers]
"X-Powered-By"="Herb-go"
"X-Frame-Options"="SAMEORIGIN"
